services:
  database:
    image: postgres:15-alpine
    container_name: disys-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: disysuser
      POSTGRES_PASSWORD: disyspw
      POSTGRES_DB: energydb           # legt eine default-Datenbank an
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: disys-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: rabbit   # eigene User/Pass
      RABBITMQ_DEFAULT_PASS: rabbit123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  db_data:
  rabbitmq_data:
